---
- hosts: 10.0.0.5
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt:
      name: apache2
      state: present
  - name: copy test file into node side
    copy:
      src: mytestfile
      dest: /home/maha/

  - name: downlaod any internet file into  node side 
    get_url:
      url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
      dest: /home/maha/apache-tomcat-10.0.20.tar.gz
      force_basic_auth: yes

  - name: copy indexfile into node side
    template:
       src:  myindex.j2
       dest: /var/www/html/index.html
    notify: restartwebserver
      

  handlers:
  - name: restartwebserver
    service:
       name: apache2
       state: restart 
    
  


